### PR TITLE
added .env option rather than requiring it at the command line

### PR DESCRIPTION
**Pull request by vdavez**
Seemed like using a config file (in the form of a `.env` file) is easier and less error prone than command line). For implementation, you'd need to run `mv .env.example .env` first and make appropriate changes, but then it's  the same.

### CODE REVIEW

**Comment by RobertLRead** [comment]
Thanks, Dave, this looks pretty good---have you tested it?  And I think we would need to change the README as well, right?  If you do those things I'll merge this PR.

**Comment by vdavez** [comment]
Thanks Rob! I haven't tested yet (I'll do it tonight) and when I do, I'll update the readme.

**Comment by vdavez** [comment]
Meanwhile, I can't seem to open an "issue." So, I'll ask here:

Are additional functions in the pipeline/desirable? For example, it might make sense to take advantage of some of gh-pages support for jekyll. 

Similarly, I'm not sure if this is intended, but have you considered renaming the `origin` remote to be `downstream` rather than simply writing over it. That way if there are feature updates to the cloned site, you can merge them more easily. Just a thought.

**Comment by RobertLRead** [comment]
Pulling in Gray, who did something similar about stream management, though
he may have done it on the template.

I'll try to figure out why you can't create an issue.

I hope Gray can comment on them --- I created this repo a while back, but I
honestly not sure how much 18F is using it---Gray, Eric Mill, etc. may no
better how and if this is being used.

1) Although named "microsite-18F", this code actually is NOT specific to
18F---we put all of that stuff in the template.  So my opinion would be
that when 18F starts using Jekyll generally, we should create a Jekyll-ized
template to pull from, but that it should NOT go into this functionality.

As to the origin/downstream issue --- No, it was not intended, in fact you
probably understand the issues better than I do for modern GitHub usage.
Gray renamed one of the branches on the template---I think.  Whatever you
think is best---probably is best.

On Mon, Feb 2, 2015 at 10:15 AM, V David Zvenyach notifications@github.com
wrote:

> Meanwhile, I can't seem to open an "issue." So, I'll ask here:
> 
> Are additional functions in the pipeline/desirable? For example, it might
> make sense to take advantage of some of gh-pages support for jekyll.
> 
> Similarly, I'm not sure if this is intended, but have you considered
> renaming the origin remote to be downstream rather than simply writing
> over it. That way if there are feature updates to the cloned site, you can
> merge them more easily. Just a thought.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/microsite-18f/pull/1#issuecomment-72473535.

## 

Robert L. Read, PhD
Managing Director, 18F Consulting http://18f.github.io/consulting/
(202) 809-1941

**Comment by gbinal** [comment]
> I'll try to figure out why you can't create an issue.

It's a setting that may have flipped off when the project was forked.  Fixed.

**Comment by gbinal** [comment]
@vzvenyach - you're totally right about changing the origin though I'm afraid I'm a bit of a github lightweight in this area.  I'll spin up a separate issue for that, so that this thread can focus on your PR.

**Comment by monfresh** [comment]
This would also require adding a `.gitignore` and adding `.env` to it so that you don't push your sensitive information to this public repo.

**Comment by vdavez** [comment]
good call.

**Comment by vdavez** [comment]
Ok, so I tested it out and the proof lives here: http://code.esq.io/microsite/

If the PR is merged, issue #1 #2 and #3 are all resolved.

**Comment by RobertLRead** [comment]
Thanks, Dave--- pull request is merged.

On Mon, Feb 2, 2015 at 7:55 PM, V David Zvenyach notifications@github.com
wrote:

> Ok, so I tested it out and the proof lives here:
> http://code.esq.io/microsite/
> 
> If the PR is merged, issue #1
> https://github.com/18F/microsite-18f/pull/1 #2
> https://github.com/18F/microsite-18f/issues/2 and #3
> https://github.com/18F/microsite-18f/issues/3 are all resolved.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/microsite-18f/pull/1#issuecomment-72571450.

## 

Robert L. Read, PhD
Managing Director, 18F Consulting http://18f.github.io/consulting/
(202) 809-1941

**Pull request merged**
